### PR TITLE
Courtney

### PR DESCRIPTION
**Pull request by clburns107**
I think i need some guidance on what Im looking for in the random department... Im currently staring at scripts and I dont know if im on the right path.

### CODE REVIEW

**Comment by halfghaninne** [comment]
Read your final commit message. Steps for this could be:
1. Work on _just_ getting Dopey pulled up dynamically from the database
2. Work on getting another dwarf pulled up as Dopey's competitor
3. Figure out how to randomize _any_ two dwarfs

Does that help?

**Comment by clburns107** [comment]
Im still confused. Because i thought that dynamically mean that if one situation changed another situation changed with it.  Where there is really just random, right? So i guess my question is I dont know how to display an option randomly.

**Comment by halfghaninne** [comment]
Dynamically means pulling information from the database, rather than hardcoding it into the HTML.

**Comment by clburns107** [comment]
all tests are passing but method is broken...last 3 commit messages explain but short vs. im pretty sure loop is not finishing.

**Pull request closed without merging**
